encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
pygments: true

# 作者信息
author: 
  name: 杨帅
  email: sherkyoung@gmail.com
  link: http://sherkyoung.github.io/
  weibo: http://weibo.com/yangshuailogo
  github: https://github.com/sherkyoung



# 站点信息
title: Phoenix
description: 
 通信系的学生,误打误撞进入了计算机行业,吃力的摸爬滚打.fighting!!!
url: http://sherkyoung.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.ico

# disqus 设置
#disqus:
#  shortname: sherk

#profile 个人信息

profile_desc : 任谁都有迷茫和困惑<br>我能做的就是不断求知<br>前进的道路上免不了风雨<br>唯有始终如一<br>

# 首页除了最新文章外显示分类
cates: 
#- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章